### ISSUE TITLE
unknown field "spec.targetRef.namespace"

### ISSUE THREAD

**Issue by leathersole** [Kuadrant/kuadrantctl#100]
```
kuadrantctl generate kuadrant ratelimitpolicy --oas https://raw.githubusercontent.com/Kuadrant/kuadrantctl/refs/heads/main/examples/oas3/petstore-with-oidc-kuadrant-extensions.yaml
```
This command generates following yaml but `spec.targetRef.namespace` is invalid field and causes error.
```
apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  creationTimestamp: null
  name: petstore
  namespace: petstore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: petstore
    namespace: petstore
status: {}
```
```
Error from server (BadRequest): error when creating "STDIN": RateLimitPolicy in version "v1beta2" cannot be handled as a RateLimitPolicy: strict decoding error: unknown field "spec.targetRef.namespace"
```

Same issue occurs when I generate AuthPolicy
```
$ kuadrantctl generate kuadrant authpolicy --oas https://raw.githubusercontent.com/Kuadrant/kuadrantctl/refs/heads/main/examples/oas3/petstore-with-oidc-kuadrant-extensions.yaml |kubectl apply -f -
Error from server (BadRequest): error when creating "STDIN": AuthPolicy in version "v1beta2" cannot be handled as a AuthPolicy: strict decoding error: unknown field "spec.targetRef.namespace"
```
